# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

elasticsearch:
  clusterName: haco-es-address-search
  masterTerminationFix: true
  replicas: 1
  minimumMasterNodes: 1

  resources:
      requests:
        cpu: "100m"
        memory: "512M"
      limits:
        cpu: "200m"
        memory: "2Gi"
  env:
    XPACK_MONITORING_ENABLED: "true"

kibana:
  clusterName: haco-es-address-search
  replicas: 1
  minimumMasterNodes: 1
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "200m"
      memory: "512M"
  env:
    XPACK_MONITORING_ENABLED: "true"

metricbeat:
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "200m"
      memory: "512M"
